services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    ports: ["8000:8000"]
    volumes: ["./.data/dynamodb:/data"]

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports: ["8001:8001"]
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on: [dynamodb]

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: local
      MINIO_ROOT_PASSWORD: locallocal
    volumes: ["./.data/minio:/data"]

  stepfunctions:
    image: amazon/aws-stepfunctions-local:latest
    ports: ["8083:8083"]
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCOUNT_ID: "123456789012"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      LAMBDA_ENDPOINT: http://host.docker.internal:4011
    extra_hosts: ["host.docker.internal:host-gateway"]